a=input(('Digite algo: '))
print('O tipo primitivo desse valor é: ',type(a))
print('É um Alfanumerico?', a.isalnum())
print('Tem espaço?', a.isspace())
print('É decimal?', a.isdecimal())
print('É uma letra?', a.isalpha())
print('É um numero?', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('Está em maiúscula?', a.isupper())
print('Está em minuscula?', a.islower())
print('Está capitalizada?', a.istitle())